### ISSUE TITLE
Make report for Sprint 1 deliverable

### ISSUE THREAD

**Issue by jestapinski** [stephaniepang97/thoughtful#1]
we need to do this!

**Comment by stephaniepang97** [comment]
How well does the app fit in with the mobile mindset?

Does this app utilize any of the strengths of the mobile platform?

What are the main features of the app?

Who are the target users of the application?

What is the pain point that your app addresses?

What is the value provided by the app?

What is your app’s lifespan? Opportunity for return users?

What has been learned from user research performed to date to support these positions?

What (if any) existing APIs are you planning on using?

What is the biggest foreseeable challenge for implementation?
